### ISSUE TITLE
Support for unicode surrogate pairs

### ISSUE THREAD

**Issue by sindresorhus** [chalk/wrap-ansi#11]
https://mathiasbynens.be/notes/javascript-unicode

I've added a failing skipped test: https://github.com/chalk/wrap-ansi/commit/970e1a71e13adbe4385be751cfa42adf650a8b71

**Comment by kevva** [comment]
Would it be okay if I rewrote it to using ES2015 syntax? This is so we can iterate through them like https://github.com/chalk/slice-ansi/pull/8/files#diff-168726dbe96b3ce427e7fedce31bb0bcR50. Without `for...of` we'd need to introduce some looping logic that does this for us.

**Comment by sindresorhus** [comment]
Sure

**Comment by sindresorhus** [comment]
@kevva This module is now using ES2015 syntax, although I might have missed something. Interested in resolving this issue here too?

**Comment by kevva** [comment]
Oh, nice that you beat me to it :). I'll take a look at it tonight!
