### ISSUE TITLE
Newline handling in 6.0.0

### ISSUE THREAD

**Issue by unindented** [chalk/wrap-ansi#39]
In `wrap-ansi@5.0.0` all newlines are converted properly:

```js
const wrapAnsi = require("wrap-ansi@5.0.0")
console.log(wrapAnsi('a\r\n\r\nb', 5)) // outputs "a\n\nb"
```

In `wrap-ansi@6.0.0` not all newlines are converted:

```js
const wrapAnsi = require("wrap-ansi@6.0.0")
console.log(wrapAnsi('a\r\n\r\nb', 5)) // outputs "a\r\n\nb"
```

**Comment by kevva** [comment]
In `5.1.0` I get the same result as in `6.0.0`. I think the change happened in https://github.com/chalk/wrap-ansi/pull/33 which was merged after `5.0.0`.

**Comment by unindented** [comment]
Fair enough. So I guess this is a "Won't fix"?

**Comment by kevva** [comment]
It needs to be addressed in some way. Currently the output it neither untouched or completely normalized. We just need to decide on how we want it to work. I'll let others chime in before submitting a PR.

**Comment by sindresorhus** [comment]
I think it's totally fine for us to normalize newlines as long as we document the behavior. It's the wanted behavior in most cases.
