### ISSUE TITLE
Can't install package / EEXIST

### ISSUE THREAD

**Issue by scottmwyant** [chalk/wrap-ansi#44]
Running `npm install --save-dev wrap-ansi` results in the following error:

```
npm ERR! code EEXIST
npm ERR! syscall mkdir
npm ERR! path ...\test\node_modules\wrap-ansi\node_modules
npm ERR! errno -4075
npm ERR! EEXIST: file already exists, mkdir '...\test\node_modules\wrap-ansi\node_modules'
npm ERR! File exists: ...\test\node_modules\wrap-ansi\node_modules
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

```

npm: 6.14.6
node: v12.18.4
os: Windows 10 (10.0.18363)

Note that I have node and npm installed in the user context (C:\users\user\AppData\Local\Programs\nodejs\[node.exe | npm.cmd]).

Please advise.  This is preventing me from installing [mocha](https://www.npmjs.com/package/mocha).

**Comment by sindresorhus** [comment]
This is not the place to ask for npm support => https://www.npmjs.com/support
