### ISSUE TITLE
Add a `ambiguousIsNarrow` option 

### ISSUE THREAD

**Issue by ehmicky** [chalk/wrap-ansi#47]
Some users might want to override the default value for the `string-width` [option `ambiguousIsNarrow`](https://github.com/sindresorhus/string-width#ambiguousisnarrow). See https://github.com/sindresorhus/string-width/issues/38 about reasons why they might want this.

Therefore, this library should allow passing that option.

Note: I can submit a PR if this sounds good.

**Comment by sindresorhus** [comment]
Now that it's fixed in `string-width`, do you still need this? Otherwise, I prefer to wait until someone actually needs this before exposing an option for it.

**Comment by ehmicky** [comment]
Exactly, this is not needed anymore, and I agree adding an option is not helpful anymore then. Thanks!
