### ISSUE TITLE
Take into account line returns inside input

### ISSUE THREAD

**Issue by SBoudrias** [chalk/wrap-ansi#7]
I think this module should take into account line returns already present into the input.

For example, currently:

```js
var input = '12345678\n901234567890';

console.log(wrapAnsi(input, 10, {hard: true}));
```

will print

```
12345678
9
0123456789
0
```

I'd expect:

```
12345678
9012345678
90
```

**Comment by bcoe** [comment]
:+1: this would have actually helped me with the module:

http://github.com/bcoe/yarsay

Which I was working on this weekend. Would you like to take a stab at implementing this? I think we should probably treat it as a breaking change., we can pull it into yargs@4.x.

**Comment by dthree** [comment]
This implementation looks simple enough.

**Comment by SBoudrias** [comment]
> Would you like to take a stab at implementing this?

Sorry, I got too much things to do already on my others projects.

**Comment by dthree** [comment]
Okay went ahead and fixed this:

https://github.com/chalk/wrap-ansi/pull/8

Would like some review before merging.
